-- Create the database if it doesn't already exist
CREATE DATABASE IF NOT EXISTS UniversityDB;

-- Use the newly created or existing database
USE UniversityDB;

-- Create the COLLEGE table
CREATE TABLE COLLEGE (
  CName VARCHAR(255) PRIMARY KEY,
  COffice VARCHAR(255),
  CPhone VARCHAR(20)
);

-- Create the DEPT (DEPARTMENT) table
CREATE TABLE DEPT (
  DName VARCHAR(255) PRIMARY KEY,
  DCode VARCHAR(20) NOT NULL UNIQUE,
  DOffice VARCHAR(255),
  DPhone VARCHAR(20),
  CName VARCHAR(255),
  FOREIGN KEY (CName) REFERENCES COLLEGE(CName)
);

-- Create the CHAIR table
CREATE TABLE CHAIR (
  DName VARCHAR(255),
  CStartDate DATE,
  PRIMARY KEY (DName),
  FOREIGN KEY (DName) REFERENCES DEPT(DName)
);

-- Create the INSTRUCTOR table
CREATE TABLE INSTRUCTOR (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  IName VARCHAR(255) NOT NULL,
  `Rank` VARCHAR(255),
  IOffice VARCHAR(255),
  IPhone VARCHAR(20),
  DName VARCHAR(255),
  FOREIGN KEY (DName) REFERENCES DEPT(DName)
);

-- Create the STUDENT table
CREATE TABLE STUDENT (
  SId INT PRIMARY KEY AUTO_INCREMENT,
  FName VARCHAR(255),
  MName VARCHAR(255),
  LName VARCHAR(255),
  SName VARCHAR(255),
  DOB DATE,
  Addr VARCHAR(255),
  Phone VARCHAR(20),
  Major VARCHAR(255)
);

-- Create the COURSE table
CREATE TABLE COURSE (
  CCode VARCHAR(20) PRIMARY KEY,
  Credits INT,
  CoName VARCHAR(255) NOT NULL,
  CDesc TEXT,
  Level VARCHAR(10),
  DName VARCHAR(255),
  FOREIGN KEY (DName) REFERENCES DEPT(DName)
);

-- Create the SECTION table
CREATE TABLE SECTION (
  SecId INT PRIMARY KEY AUTO_INCREMENT,
  SecNo INT,
  Sem VARCHAR(255),
  Year INT,
  DaysTime VARCHAR(255),
  CRoom VARCHAR(255),
  Bldg VARCHAR(255),
  RoomNo VARCHAR(255),
  CCode VARCHAR(20),
  FOREIGN KEY (CCode) REFERENCES COURSE(CCode)
);

-- Create the TEACHES table
CREATE TABLE TEACHES (
  Id INT,
  SecId INT,
  PRIMARY KEY (Id, SecId),
  FOREIGN KEY (Id) REFERENCES INSTRUCTOR(Id),
  FOREIGN KEY (SecId) REFERENCES SECTION(SecId)
);

-- Create the TAKES table
CREATE TABLE TAKES (
  SId INT,
  SecId INT,
  Grade CHAR(2),
  PRIMARY KEY (SId, SecId),
  FOREIGN KEY (SId) REFERENCES STUDENT(SId),
  FOREIGN KEY (SecId) REFERENCES SECTION(SecId)
);

-- Create the ADMIN table
CREATE TABLE ADMIN (
  Id INT PRIMARY KEY,
  DName VARCHAR(255),
  FOREIGN KEY (Id) REFERENCES INSTRUCTOR(Id),
  FOREIGN KEY (DName) REFERENCES DEPT(DName)
);

-- Create the DEAN table
CREATE TABLE DEAN (
  Id INT PRIMARY KEY,
  CName VARCHAR(255),
  FOREIGN KEY (CName) REFERENCES COLLEGE(CName),
  FOREIGN KEY (Id) REFERENCES INSTRUCTOR(Id)
);

-- Create the EMPLOYS table
CREATE TABLE EMPLOYS (
  DName VARCHAR(255),
  Id INT,
  PRIMARY KEY (DName, Id),
  FOREIGN KEY (DName) REFERENCES DEPT(DName),
  FOREIGN KEY (Id) REFERENCES INSTRUCTOR(Id)
);
