CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE DEPARTMENT (
    DNUMBER INT PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL,
    MGRSSN VARCHAR(9) NOT NULL,
    MGRSTARTDATE DATE
);

CREATE TABLE EMPLOYEE (
    SSN VARCHAR(9) PRIMARY KEY,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    BDATE DATE,
    ADDRESS VARCHAR(100),
    SEX CHAR(1),
    SALARY DECIMAL(10, 2),
    SUPERSSN VARCHAR(9),
    DNO INT
);
CREATE TABLE PROJECT (
    PNUMBER INT PRIMARY KEY,
    PNAME VARCHAR(50) NOT NULL,
    PLOCATION VARCHAR(50),
    DNUM INT
);

CREATE TABLE WORKS_ON (
    ESSN VARCHAR(9),
    PNO INT,
    HOURS DECIMAL(3, 1),
    PRIMARY KEY (ESSN, PNO)
);

CREATE TABLE DEPENDENT (
    ESSN VARCHAR(9),
    DEPENDENT_NAME VARCHAR(50),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(50),
    PRIMARY KEY (ESSN, DEPENDENT_NAME)
);

-- Inserting into DEPARTMENT
INSERT INTO DEPARTMENT (DNUMBER, DNAME, MGRSSN, MGRSTARTDATE) VALUES
(1, 'Headquarters', '987654321', '2019-06-19'),
(5, 'Research', '123456789', '2020-01-01');

-- Inserting into EMPLOYEE
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, BDATE, ADDRESS, SEX, SALARY, SUPERSSN, DNO) VALUES
('123456789', 'John', 'Smith', '1973-11-09', '731 Fondren, Houston, TX', 'M', 30000.00, NULL, 5),
('987654321', 'Franklin', 'Wong', '1955-12-08', '638 Voss, Houston, TX', 'M', 40000.00, '123456789', 1),
('111223333', 'Alice', 'Johnson', '1980-05-05', '123 Main St, Houston, TX', 'F', 28000.00, '123456789', 5),
('222334444', 'Michael', 'Brown', '1978-09-15', '456 Elm St, Houston, TX', 'M', 35000.00, '987654321', 1);

-- Inserting into PROJECT
INSERT INTO PROJECT (PNUMBER, PNAME, PLOCATION, DNUM) VALUES
(1, 'ProductX', 'Bellaire', 5),
(2, 'ProductY', 'Sugarland', 5);

-- Inserting into WORKS_ON
INSERT INTO WORKS_ON (ESSN, PNO, HOURS) VALUES
('123456789', 1, 20.0),
('987654321', 2, 15.0);

-- Inserting into DEPENDENT
INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP) VALUES
('123456789', 'Alice', 'F', '1986-04-05', 'Daughter'),
('987654321', 'John', 'M', '1992-09-15', 'Son');
-- Adding foreign key constraints to DEPARTMENT
ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_MGRSSN FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN);

-- Adding foreign key constraints to EMPLOYEE
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_SUPERSSN FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN),
ADD CONSTRAINT FK_DNO FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);

-- Adding foreign key constraints to PROJECT
ALTER TABLE PROJECT
ADD CONSTRAINT FK_DNUM FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER);

-- Adding foreign key constraints to WORKS_ON
ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_ESSN FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
ADD CONSTRAINT FK_PNO FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER);

-- Adding foreign key constraints to DEPENDENT
ALTER TABLE DEPENDENT
ADD CONSTRAINT FK_DEPENDENT_ESSN FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E, WORKS_ON W, PROJECT P
WHERE E.SSN = W.ESSN AND W.PNO = P.PNUMBER AND P.PNAME = 'ProductX' AND E.DNO = 5 AND W.HOURS > 10;
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E, DEPENDENT D
WHERE E.SSN = D.ESSN AND E.FNAME = D.DEPENDENT_NAME;
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE E, EMPLOYEE S
WHERE E.SUPERSSN = S.SSN AND S.FNAME = 'John' AND S.LNAME = 'Smith';
